famous_books_dict = {
    "To Kill a Mockingbird": "Harper Lee",
    "1984": "George Orwell",
    "The Great Gatsby": "F. Scott Fitzgerald",
    "Pride and Prejudice": "Jane Austen",
    "The Catcher in the Rye": "J.D. Salinger",
    "The Lord of the Rings": "J.R.R. Tolkien",
    "Harry Potter and the Sorcerer's Stone": "J.K. Rowling",
    "The Hobbit": "J.R.R. Tolkien",
    "The Alchemist": "Paulo Coelho",
    "The Da Vinci Code": "Dan Brown",
    "Moby-Dick": "Herman Melville",
    "War and Peace": "Leo Tolstoy",
    "Crime and Punishment": "Fyodor Dostoevsky",
    "The Kite Runner": "Khaled Hosseini",
    "The Book Thief": "Markus Zusak",
    "Animal Farm": "George Orwell",
    "The Chronicles of Narnia": "C.S. Lewis",
    "Jane Eyre": "Charlotte Brontë",
    "The Picture of Dorian Gray": "Oscar Wilde",
    "Brave New World": "Aldous Huxley",
    "Wuthering Heights": "Emily Brontë",
    "Catch-22": "Joseph Heller",
    "Les Misérables": "Victor Hugo",
    "The Little Prince": "Antoine de Saint-Exupéry",
    "The Hunger Games": "Suzanne Collins",
    "A Game of Thrones": "George R.R. Martin",
    "The Fault in Our Stars": "John Green",
    "The Road": "Cormac McCarthy",
    "Life of Pi": "Yann Martel",
    "The Shining": "Stephen King"
}
auther=famous_books_dict["1984"]
print(auther)